### ISSUE TITLE
create  a recipe

### ISSUE THREAD

**Issue by kamathln** [niavlys/admob4kivy#1]
Please create a recipe so that all these things are automated

**Comment by niavlys** [comment]
Hi,
I'm no longer playing with Kivy anymore, and I have less spare time to address your issue. Plus, it seems that there is no consensus on how to alter the androidmanifest's template through a recipe (see https://github.com/kivy/python-for-android/issues/255).

I'd be happy to be proven I'm wrong, and will review and accept any pull request, if any (so does kivy/p4a I think)
